// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FiltersFormController from "./filters_form_controller"
import FlashController from "./flash_controller"
import AppointmentDatetime from "./appointment_datetime"

application.register("filters-form", FiltersFormController)
application.register("flash", FlashController)
application.register("appointment-datetime", AppointmentDatetime)
